Add files via upload
MitkoZ/Entrance-Counter pull request #5
Opened 2018-04-18 23:50 UTC by petiofiiito

Fixed design issues

2018-04-19 11:23 UTC, mystiquewolf commented on index.html
> +              <div style="width: 100%" class="center-chart" id="dustinessOfTheAirChart">
width: 100% is 🆒. Maybe we can remove class="center-chart" from this line now? 💭

2018-04-19 11:35 UTC, liubomirwm commented on index.html
> +        <div class="col-sm-5 col-sm-offset-1">
I believe the PM/boss said all gauge charts should be col-sm-6 without offsets, could you please ask him just for us to be absolutely sure?

2018-04-19 12:01 UTC, mystiquewolf requested changes

2018-04-19 12:01 UTC, liubomirwm commented on index.html
>                    <div class="huge">0</div>
This should be updated to match the chart on new dustiness data. If you want you can take care of it. Otherwise i will do it before merging. 😺

2018-04-20 17:57 UTC, MitkoZ commented on index.html
> +              <div style="width: 100%" class="center-chart" id="dustinessOfTheAirChart">
Ok

2018-04-22 12:36 UTC, mystiquewolf approved these changes

2018-04-22 20:45 UTC, merged